apps/login_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/travel/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.trips, name='trips'),
    url(r'^add', views.add, name='add_trip'),
    url(r'^create', views.create, name='create'),
    url(r'^destination/(?P<id>\d+)$', views.destination, name='destination'),
    url(r'^join/(?P<id>\d+)$', views.join, name='join')

]

travel_buddy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_reg.urls', namespace='login_reg')),
    url(r'^travels/', include('apps.travel.urls', namespace='trip0')),
]

apps/login_reg/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
import re, bcrypt

USERNAME_REGEX = re.compile(r'^[a-zA-Z0-9]+$')
# Create your models here.
class UserManager(models.Manager):
  def register(self, data):

    errors = []
    response = {}

    if len(data['username' and 'name' and 'password' and 'confirm_pw'])<1:
      errors.append("You cannot leave any  field blank!")
    elif len(data['name'])<3:
      errors.append("Your name must be longer than 3 characters")
    elif not (data['name']).replace(' ','').isalpha():
      errors.append("Your name can only contain letters")
    elif not USERNAME_REGEX.match(data['username']):
      errors.append("Username may not contain anything else than alphabets and numbers")
    elif len(data['password'])<8:
      errors.append("Password must be at least 8 characters long")
    elif not (data['password']==data['confirm_pw']):
      errors.append("Unable to confirm password. Please enter same password you have entered above")

    if not errors:
      password = data['password'].encode()
      hashed = bcrypt.hashpw(password, bcrypt.gensalt())
      new_user = self.create(name=data['name'], username=data['username'], password=hashed)
      response['added'] = True
      response['new_user'] = new_user


    else:
      response['added'] = False
      response['errors'] = errors

    print (errors)

    return response

  def login(self, data):
    response = {}

    user = User.objects.filter(username=data['username'])

    if user:
      user = user[0]
      pw = data['login_pw'].encode()

      if bcrypt.hashpw(pw, user.password.encode()) == user.password.encode():

        response['access'] = True
        response['User'] = user
      else:
        response ['access'] = False
    else:
      response['access'] = False
    return response




class User(models.Model):
  name = models.CharField(max_length=255)
  username = models.CharField(max_length=255)
  password = models.CharField(max_length=255)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  objects = UserManager()

apps/travel/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_reg.models import User
from datetime import datetime

# Create your models here.
class TripManager(models.Manager):
  def validation(self, data):
    now = datetime.datetime.now()
    errors=[]

    if not data['destination']:
      errors.append('Please enter your destination')
    if not data['start_date']:
      errors.append('Please enter the start date for your trip')
    if not data['end_date']:
      errors.append('Please enter the ending date for your trip')
    if data['start_date']>data['end_date']:
      errors.append('You cannot end your trip before it begins')
    if data['start_date'] < str(now):
      errors.append('Please enter a valid start date for your trip')
    if data['end_date'] < str(now):
      errors.append('Please enter a valid end date for your trip')

    response = {}
    if not errors:
      response['add'] = True
      return response

    else:
      response['add'] = False
      response['errors'] = errors
      return response

class Trip(models.Model):
  destination = models.CharField(max_length=255)
  plan = models.CharField(max_length=255)
  start_date = models.DateField()
  end_date = models.DateField()
  created_user = models.ForeignKey(User)
  joined_user = models.ManyToManyField(User, related_name='users')
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  objects = TripManager()

apps/login_reg/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
import re
from datetime import datetime
from .models import User
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):

  return render (request, 'login_reg/index.html')

def register(request):
  res = User.objects.register(request.POST)

  if res['added']:
    request.session['user_id'] = res['new_user'].id
    messages.success(request, "Success! Welcome, {}!".format(res['new_user'].name))
    request.session['notification'] = "Registered successfully"
    request.session['user_name'] = res['new_user'].name
    return redirect('trip0:trips')

  else:
    for error in res['errors']:
      messages.error(request, error)
    return redirect('login_reg:index')

def login(request):
  user = User.objects.login(request.POST)

  if user['access']:
    request.session['user_id'] = user['User'].id
    request.session['user_name'] = user['User'].name
    messages.success(request, "Success! Welcome, {}!".format(user['User'].name))
    request.session['notification'] = "Logged in successfully!"
    return redirect ('trip0:trips')

  else:
    messages.error(request, "Email/Password not found")
    return redirect('login_reg:index')

def logout(request):
  request.session.clear()
  messages.success(request, "Successfully logged out")
  return redirect('login_reg:index')

apps/travel/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Trip, User

# Create your views here.

def trips(request):
  if 'user_id' not in request.session:
    return redirect('login_reg:index')
  context = {
    'trips': Trip.objects.all().filter(created_user__id=request.session['user_id']) | Trip.objects.all().filter(joined_user__id=request.session['user_id']),
    'other_trips': Trip.objects.all().exclude(created_user__id=request.session['user_id']),
    'users': User.objects.get(id=request.session['user_id']),
  }
  return render(request, 'travel/index.html', context)

def add(request):
  if 'user_id' not in request.session:
    return redirect('login_reg:index')

  return render(request, 'travel/add.html')

def create(request):
  Trip.objects.create(destination=request.POST['destination'], plan=request.POST['description'], start_date=request.POST['start_date'], end_date=request.POST['end_date'], created_user=User.objects.get(id=request.session['user_id']))
  print (request.POST['start_date'])
  # return redirect('trip0:trips')

def destination(request, id):
  context = {
    'destination': Trip.objects.filter(id=id),
    'joined_users': User.objects.filter(users__id=id)
  }
  return render (request, 'travel/view.html', context)

def join(request, id):
  join_trip = Trip.objects.get(id=id)
  additional_user = User.objects.get(id=request.session['user_id'])
  join_trip.joined_user.add(additional_user)
  return redirect('trip0:trips')

apps/login_reg/templates/login_reg/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Login/Registration</title>
    <link rel="stylesheet" type="text/css" href=" ">
  </head>

  <body>
    <h1>Welcome!</h1>
    {% if messages %}
      {% for message in messages %}
        <p>{{message}}</p>
      {% endfor %}
    {% endif %}    

    <h3>Register</h3>
    <div class='registration'>
      <form action='register' method='POST'>
        {% csrf_token %}
        <p>Name <input type='text' name='name'></p>
        <p>Username <input type='text' name='username'></p>
        <p>Password <input type='password' name='password'></p>
        <p>*Password should be at least 8 characters</p>
        <p>Confirm PW <input type='password' name='confirm_pw'></p>
        <input type='submit' value='Register'>
      </form>
    </div>

    <h3>Login</h3>
    <div class='registration'>
      <form action='login' method='POST'>
        {% csrf_token %}
        <p>Username <input type='text' name='username'></p>
        <p>Password <input type='password' name='login_pw'></p>
        <input type='submit' value='login'>
      </form>
    </div>

  </body>

</html>

apps/travel/templates/travel/add.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Add Plan</title>
    <link rel="stylesheet" type="text/css" href=" ">
  </head>

  <body>
    {% if messages %}
      {% for msg in messages %}
        {{msg.message}}
      {% endfor %}
    {% endif %}

    <h1>Add a Trip</h1>
    
    <form action={% url 'trip0:create' %}, method="POST">
      {% csrf_token %}
      <p>Destination: <input type="text" name="destination"></p>
      <p>Description: <input type="text" name="description"></p>
      <p>Travel Date From: <input type="date" name="start_date"></p>
      <p>Travel Date To: <input type="date" name="end_date"></p>
       <input type="submit" value="Add Trip">
    </form>
  </body>

</html>

apps/travel/templates/travel/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Travel Dashboard</title>
    <link rel="stylesheet" type="text/css" href=" ">
  </head>

  <body>
    <div id='welcome'>
      {% if messages %}
        {% for message in messages %}
          <h1><p>{{message}}</p></h1>
          <p id='success'>{{ request.session.notification }}</p>
        {% endfor %}
      {% endif %}
    </div>

      <h2> Hello, {{request.session.user_name}}! </h2>

      <p>Your Trip Schedules</p>
      <table>
        <tr>
          <th>Destination</th>
          <th>Travel Start Date</th>
          <th>Travel End Date</th>
          <th>Plan</th>
        </tr>
        {% for trip in trips %}
          <tr>
            <td><a href="{% url 'trip0:destination' id=trip.id %}">{{trip.destination}}</a></td>
            <td>{{trip.start_date}}</td>
            <td>{{trip.end_date|date:"M d Y"}}</td>
            <td>{{trip.plan}}</td>
          </tr>
        {% endfor %}
      </table>

      <p>Other User's Travel Plans</p>
      <table>
        <tr>
          <th>Name</th>
          <th>Destination</th>
          <th>Travel Start Date</th>
          <th>Travel End Date</th>
          <th>Do You Want To Join?</th>
        </tr> 
        {% for trip in other_trips %}
          <tr>
            <td>{{trip.created_user.name}}</td>
            <td><a href="{% url 'trip0:destination' id=trip.id %}">{{trip.destination}}</a></td>
            <td>{{trip.start_date|date:"M d Y"}}</td>
            <td>{{trip.end_date|date:"M d Y"}}</td>
            <td><a href="{% url 'trip0:join' id=trip.id %}">Join</a></td>
          </tr>
        {% endfor %}
      </table>

    <a href="{% url 'trip0:add_trip' %}">Add Travel Plan</a>
    <form action="{% url 'login_reg:logout' %}">
      <input type='submit' value='logout'>
    </form>
  </body>

</html>

apps/travel/templates/travel/view.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Destination</title>
    <link rel="stylesheet" type="text/css" href=" ">
  </head>

  <body>
    <a href="{% url 'trip0:trips' %}">Back to main</a>
    <form action="{% url 'login_reg:logout' %}">
      <input type='submit' value='logout'>
    </form>

    {% for trip in destination %}
      <h1>{{trip.destination}}</h1>
      <p>Planned By: {{trip.created_user.name}}</p>
      <p>Description: {{trip.plan}}</p>
      <p>Travel Date From: {{trip.start_date|date:"M d Y"}}</p>
      <p>Travel Date To: {{trip.end_date|date:"M d Y"}}</p>
    {% endfor %}

    <h1>Other users joining the trip</h1>
    {% for user in joined_users %}
      <p>{{user.name}}</p>
    {% endfor %}
  </body>

</html>